### PR TITLE
Good to go

### PR DESCRIPTION
**Pull request by uilianries**
Related issue: https://github.com/conan-community/community/issues/12

I just made some points:
- Add fPIC option
- Support mingw ... and working
- Add CI badge
- Add logo
- Use external cmake wrapper instead of write on file

Regards!

### CODE REVIEW

**Comment by uilianries** [comment]
The job https://ci.appveyor.com/project/lasote/conan-c-ares/build/1.0.8/job/k5hslqy5wd3p84b7 failed because some server error. It could be restarted with no problems.

**Comment by lasote** [comment]
Great! thanks!

**Comment by uilianries** [comment]
I see the same error again. Should I run `pip install -U pip` on Appveyor script?

**Comment by lasote** [comment]
Wow, first time I see that problem. probably it is only a temporary issue?

**Comment by uilianries** [comment]
yeah, it's a temporary issue: https://status.python.org/

**Pull request merged**
